name: Deploy Project to App Engine

on:
  push:
    branches:
      - main

  # run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test and Sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Test and analyze
        run: ./gradlew test jacocoTestReport sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # since env variables already exist, I need to add the TMDB token to the existing env variables to app.yaml
      - name: Add TMDB token to existing env variables to app.yaml
        run: |
          yq -i '.env_variables.TMDB_API_TOKEN = "${{ secrets.TMDB_API_TOKEN }}"' app.yaml

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: sopra-fs25-group-19-server
          deliverables: app.yaml
          version: v1
          credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS }}

      - name: Revert app.yaml changes
        run: git checkout -- app.yaml

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
